services:
  my-sql-books:
    image: mysql:latest
    restart: always
    volumes:
      - ./init-db/init_book_db_script.sql:/docker-entrypoint-initdb.d/init_book_db_script.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_BOOKS_PASSWORD
    ports:
      - 3306

  my-sql-records:
    image: mysql:latest
    restart: always
    volumes:
      - ./init-db/init_record_db_script.sql:/docker-entrypoint-initdb.d/init_record_db_script.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_RECORDS_PASSWORD
    ports:
      - 3306

  my-sql-users:
    image: mysql:latest
    restart: always
    volumes:
      - ./init-db/init_user_db_script.sql:/docker-entrypoint-initdb.d/init_user_db_script.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_USERS_PASSWORD
    ports:
      - 3306

  main-service:
    build:
      dockerfile: Dockerfile
      context: ./main-service
    restart: always
    depends_on:
      - my-sql-books
      - eureka-service
    environment:
      spring.application.name: main-service
      server.port: 8081

      spring.datasource.url: "jdbc:mysql://my-sql-books:3306/library_main_service"
      spring.datasource.username: root
      spring.datasource.password: $MYSQL_BOOKS_PASSWORD

      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka/

      client.application.name: additional-service
      additional-service.url: http://additional-service:8082/records
    ports:
      - 8081

  additional-service:
    build:
      dockerfile: Dockerfile
      context: ./additional-service
    restart: always
    depends_on:
      - my-sql-records
      - eureka-service
    environment:
      spring.application.name: additional-service
      server.port: 8082

      spring.datasource.url: "jdbc:mysql://my-sql-records:3306/library_additional_service"
      spring.datasource.username: root
      spring.datasource.password: $MYSQL_RECORDS_PASSWORD

      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka/
    ports:
      - 8082

  auth-service:
    build:
      dockerfile: Dockerfile
      context: ./auth-service
    restart: always
    depends_on:
      - my-sql-users
      - eureka-service
    environment:
      spring.application.name: auth-service
      server.port: 8005

      spring.datasource.url: "jdbc:mysql://my-sql-users:3306/library_auth_service"
      spring.datasource.username: root
      spring.datasource.password: $MYSQL_USERS_PASSWORD

      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka/

      security.jwt.secret-key: $SECRET_JWT_KEY
      security.jwt.expiration-time: 3600000
    ports:
      - 8005

  gateway-service:
    build:
      dockerfile: Dockerfile
      context: ./gateway-service
    restart: always
    depends_on:
      - eureka-service
    environment:
      spring.application.name: gateway-service
      server.port: 8080

      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka/

      security.jwt.secret-key: $SECRET_JWT_KEY
      security.jwt.prefix: "Bearer "
    ports:
      - 8080:8080

  eureka-service:
    build:
      dockerfile: Dockerfile
      context: ./eureka-service
    restart: always
    depends_on:
      - my-sql-users
    environment:
      spring.application.name: eureka-server
      server.port: 8761
    ports:
      - 8761
