server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/books/**
          filters:
            - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true