server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/**
eureka:
  client:
    healthcheck:
      enabled: true